### ISSUE TITLE
Bug: Info-Event missing Layer, Feature and ScreenPosition while WorldPosition does not match click position

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#189]
See the sample attached to this issue. Using latest versions included Mapsui 1.0.6. You can find the relevant code in the MainPage.xaml.cs file. I was not able to test it on iOS yet. The problem occured on Android. 

I generate a Feature at Point 0, 0 and if I click on it I get this from the Info-Event: 
```
[0:] Info Event was invoked.
[0:] Layername: 
[0:] Feature Label: 
[0:] Feature Type: 
[0:] World Postion: 35393129.2808 , -54931069.2575
[0:] Screen Postion:  , 
```

[MapsuiFormsTest.zip](https://github.com/pauldendulk/Mapsui/files/979280/MapsuiFormsTest.zip)

**Comment by pauldendulk** [comment]
I was just about to send you a message about v1.0.7 that should fix this problem. Could you check.

**Comment by Sebastian1989101** [comment]
The result now looks like this: 
```
[0:] Info Event was invoked.
[0:] Layername: 
[0:] Feature Label: 
[0:] Feature Type: 
[0:] World Postion: -20542.7452 , 38102.4502
[0:] Screen Postion: 142.2154 , 310.9141
```

still missing the Layer and Feature in the Info-EventArgs. The only thing I changed from the above sample app is the Mapsui Version from 1.0.6 to 1.0.7.

**Comment by pauldendulk** [comment]
Then I assume there is another density issue caused by Forms. You mentioned in another conversation that the tiles are small, this indicates the same.  For me it is hard to deal with these Forms issues because I am not using it. Is it possible to create a minimal sample showing this issue? You could use the InfoLayerSample of Mapsui.Samples.Android and put this is in an Form app that uses your Android Forms 'renderer'.

Perhaps first you could confirm that the current Info sample in Mapsui.Samples.Android works correctly for you, and then go on to show it does not work correctly in your forms renderer.

**Comment by Sebastian1989101** [comment]
Did you take a look at the first post of this issue? It has a very small application attached (Xamarin.Forms, just the OpenStreetMap with a single Feature Point).

**Comment by Sebastian1989101** [comment]
Well I guess I found the Problem. 
`new Feature { Geometry = new Point(0, 0), ["Label"] = "My Feature Label", ["Type"] = "My Feature Type" };`

the problem seems to appear, when I'm not exactly hitting the 0,0 position. Besides I found another issue both on iOS and Android. When two icons overlay each other, the info event is invoked for the bottom icon and not for the top one.

**Comment by pauldendulk** [comment]
oh sorry! Missed the zip. I'll take a look tonight.

**Comment by pauldendulk** [comment]
- The issue with the overlap should be random, sometimes the top one, sometime the bottom one. In the Info method the features are ordered by distance. The idea was that you would find your target quicker in the list, but I can remove that optimization.
- About hitting the exact middle. It should not work like that, everything within the bounding rectangle should be a hit. The scale should be taken into account somehow.

**Comment by pauldendulk** [comment]
I created two new issues for the observations above https://github.com/pauldendulk/Mapsui/issues/191
https://github.com/pauldendulk/Mapsui/issues/192

**Comment by pauldendulk** [comment]
This issue itself, not taking into account scale for the Info event, was fixed in 1.0.7.
