### ISSUE TITLE
Wrong scaling if using SplitView after resizing 

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#238]
When resizing the app in iOS 9 and newer SplitView, the map does not properly rerender and everything got stretch / squeezed. Take a look at the attached screenshot: 
![img_0009](https://user-images.githubusercontent.com/25636075/31857097-e5308ac2-b6d4-11e7-93fe-fd44172253eb.PNG)

**Comment by Sebastian1989101** [comment]
After note: I was not able to reproduce it in the simulator so it might be a device only bug because the screenshot comes from a TestFlight version of my app. But it happens on all of my three iPads (one with the latest Beta iOS 11.1; all others with iOS 11).

**Comment by pauldendulk** [comment]
I pushed a pre-release where I added some old code that got lost. I have not tested in the SplitView mode which you describe. Perhaps you could test it:

https://www.nuget.org/packages/Mapsui/1.1.3-pre1

To install a nuget pre-release you need to install that specific version. It does not show up as in update in the visual studio IDE.

**Comment by Sebastian1989101** [comment]
Hi Paul, 

it seems to work with iOS icon clicking again. Also the SplitView error is not reproducible (at least in the Simulator). I will test the SplitView with my next TestFlight version. 
Mit freundlichen Grüßen, 
Sebastian Kruse

  <http://kruse-familie.eu/>

**Comment by Sebastian1989101** [comment]
Hi Paul, 

I found a few hours of time today to test the 1.1.3 Pre Release version a bit more. The SplitView problem is still present but could easily be avoided by triggering a View change on Mapsui when the device rescales (ViewChanged(true)). 

But since the last update I got a strange border around the Mapsui Control (also on native iOS - did not tested Android yet about this „bug“). See the attached screenshot, I mean the white border. 

Is there already an option to relocate the copyright text for iPhone X? Because the device arrives tomorrow and I guess it is not so nice to have it behind the App-Switcher-Bar. 



Mit freundlichen Grüßen, 
Sebastian Kruse

  <http://kruse-familie.eu/>

**Comment by pauldendulk** [comment]
It looks like the screenshot is missing.

The attribution issue is not fixed. Perhaps I should just make it smaller.

Paul

**Comment by pauldendulk** [comment]
Hi Sebastian,

The iOS simulator is so slow with the new hardware accelerated skia view
that it is hard to even properly test it. It even seems to malfunction when
zooming in. Is your experience the same?

About the attribute placement. I had a quick look but am not even sure how
to fix it. Would the top be better? I would not like to give it more
prominence. On my simulator the text was at the bottom but actually still
above the button (in landscape mode) but it looks quite ugly. Perhaps it
should be really small and touching the bottom to be below the home button.

Paul

**Comment by Sebastian1989101** [comment]
Hi Paul, 

 

no, I don’t have any problems with the simulator but everyone in my team is using the 2017 MBP with max configuration so we use very strong hardware. I will test it on my old 2010 MBP when it is done with the updates (I didn’t use it for quite a while), maybe I will encounter the same problems there. It runs also very smooth on a iPhone 4S even on my Xamarin.Forms apps so I don’t guess there will be much difference on the 2010 MBP Simulator. 

 

About the placement and the problems with the iPhone X: There is a way to figure out what the “SafeArea” is. I had to face the same problems for my Zoom-Slider in my Zelda and Mario App so I used the SafeArea Margin to determine where to place it – maybe this will also work for the attribute placement? Here is how it would work (keep in mind that this is only available on iOS 11+ devices. If you try to access this on older iOS versions, you will get an Objective-C Exception.): https://forums.xamarin.com/discussion/comment/301777/#Comment_301777 

 

I don’t know if something similar is available on Android. Because it is also a small Problem on the Galaxy S8 because of the rounded corners. And I know that the Android OS has an option since Android 8 Oreo for a similar cutout as the iPhone X has on top. So there might be devices with the same problem in the future. Just using the position on top might interfere with this cutout (if the app goes to fullscreen) so I guess the SafeArea Margin would be the cleanest solution to all devices. 

 

 

Von: Paul den Dulk [mailto:notifications@github.com] 
Gesendet: Sonntag, 5. November 2017 21:04
An: pauldendulk/Mapsui <Mapsui@noreply.github.com>
Cc: Sebastian Kruse <sebastian@kruse-familie.eu>; Author <author@noreply.github.com>
Betreff: Re: [pauldendulk/Mapsui] Wrong scaling if using SplitView after resizing (#238)

 

Hi Sebastian,

The iOS simulator is so slow with the new hardware accelerated skia view
that it is hard to even properly test it. It even seems to malfunction when
zooming in. Is your experience the same?

About the attribute placement. I had a quick look but am not even sure how
to fix it. Would the top be better? I would not like to give it more
prominence. On my simulator the text was at the bottom but actually still
above the button (in landscape mode) but it looks quite ugly. Perhaps it
should be really small and touching the bottom to be below the home button.

Paul

**Comment by Sebastian1989101** [comment]
Hi Paul, 

just had the time to test it on my older systems and yes, I have the same problem there as you describe. At least on my primary development machine (MBP 2017) this does not happen. 

Did you already found the reason for the white border in the preview version? It looks pretty strange: https://puu.sh/yh4hH/0c3b470391.png <https://puu.sh/yh4hH/0c3b470391.png> (it’s there since the Preview version and the versions before don’t work for me because of the missing click info - except for the very old versions with the NuGet limitations). 
Mit freundlichen Grüßen, 
Sebastian Kruse

  <http://kruse-familie.eu/>

**Comment by pauldendulk** [comment]
Is this the white border you are referring too (see arrows):
[image: Inline image 1]

or this:
[image: Inline image 2]

About the performance in the simulator. I am happy it is no problem on
newer machines. My machine is not that old either, I would expect more
performance, but I think I will just accept it because it is just the
simulator.

Paul

**Comment by Sebastian1989101** [comment]
Hi Paul, 

 

I didn’t see any attached images. But I mean the border directly in the map frame (the one that is only visible at the left and top side). 

 

Von: Paul den Dulk [mailto:notifications@github.com] 
Gesendet: Mittwoch, 8. November 2017 16:59
An: pauldendulk/Mapsui <Mapsui@noreply.github.com>
Cc: Sebastian Kruse <sebastian@kruse-familie.eu>; Author <author@noreply.github.com>
Betreff: Re: [pauldendulk/Mapsui] Wrong scaling if using SplitView after resizing (#238)

 

Is this the white border you are referring too (see arrows):
[image: Inline image 1]

or this:
[image: Inline image 2]

About the performance in the simulator. I am happy it is no problem on
newer machines. My machine is not that old either, I would expect more
performance, but I think I will just accept it because it is just the
simulator.

Paul

**Comment by pauldendulk** [comment]
Do you see the same white line if you use the openstreetmap layer?

Paul

**Comment by Sebastian1989101** [comment]
Hi Paul, 

yes it also happens on the OSM Layer. But always the left and top site only on iOS since the preview version. https://puu.sh/yhKWf/efbff5a402.png <https://puu.sh/yhKWf/efbff5a402.png>

Mit freundlichen Grüßen, 
Sebastian Kruse

  <http://kruse-familie.eu/>

**Comment by pauldendulk** [comment]
I now also call a Refresh on the resize events, so the ViewChange(true) should not be necessary any more.

**Comment by pauldendulk** [comment]
Fixed in 1.1.3 https://github.com/pauldendulk/Mapsui/releases/tag/1.1.3

**Comment by Sebastian1989101** [comment]
Still got the strange looking white border at the left and top side as you can see here: https://puu.sh/yiwM1/db7e29e37c.png

**Comment by charlenni** [comment]
In this cases I try to start with changing the background color of any possible view. One of them should change the white border to another color. Perhaps it isn‘t MapsUI?

**Comment by pauldendulk** [comment]
I created a new issue for this, please post there: https://github.com/pauldendulk/Mapsui/issues/245

**Comment by pauldendulk** [comment]
I consider the scaling issue closed.
